version: "3.8"

services:
  proxy:
    image: hoxirious/node:latest
    working_dir: /app/proxy
    build:
      context: ./proxy/
      dockerfile: Dockerfile
    volumes:
      - ./proxy:/app/proxy
      - /app/proxy/node_modules
    ports:
      - "3000:3000"
    command: pnpm start:docker
    depends_on:
      - backend

  backend:
    image: hoxirious/node:latest
    working_dir: /app/server
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    ports:
      - "3001:3001"
      - "3002:3002"
    command: pnpm start:docker
    # deploy:
    #   replicas: 3
    #   placement:
    #     constraints:
    #       - "node.role == manager"

  mongodb:
    image: "mongo"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
    container_name: database
    ports:
      - "27017:27017"
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: cpsc559
    env_file:
      - .env
    depends_on:
      - backend


  frontend:
      image: hoxirious/node:latest
      working_dir: /app/client
      build:
        context: ./client/
        dockerfile: Dockerfile
      volumes:
        - ./client:/app/client
        - /app/client/node_modules
      ports:
        - "5173:5173"
      command: "pnpm dev"

volumes:
  mongodb_data:

